### ISSUE TITLE
NotFoundError: Not Found http-assert

### ISSUE THREAD

**Issue by uigormarshall** [gothinkster/koa-knex-realworld-example#10]
Can you help me? when configuring the project and trying to exercise the user registry, I get the following error:
```
{ NotFoundError: Not Found
    at Object.assert (/home/marshall-mint/Documentos/JS/koa-knex-realworld-example/node_modules/http-assert/index.js:8:9)
    at module.exports (/home/marshall-mint/Documentos/JS/koa-knex-realworld-example/src/middleware/error-middleware.js:7:9)
    at process.internalTickCallback (internal/process/next_tick.js:77:7) message: 'Not Found' }
```

**Comment by dimonnwc3** [comment]
@uigormarshall could you provide more info, please

which endpoint you are trying to access
what HTTP method do you use
which data do you send (in case you send it)

**Comment by uigormarshall** [comment]
Sorry, I already found the problem, uri was missing the / api.
